name: ci

on:
  push

jobs:
  rust_compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cargo build
        run: |
          cargo build --release

      - name: cargo test
        run: |
          cargo test --release

      - name: cargo dc
        run: |
          cargo doc --release --no-deps

      - name: cargo deny
        run: |
          export CARGO_DENY_VERSION="0.13.9"
          export DENY_RELEASE="cargo-deny-${CARGO_DENY_VERSION}-x86_64-unknown-linux-musl"
          wget https://github.com/EmbarkStudios/cargo-deny/releases/download/${CARGO_DENY_VERSION}/${DENY_RELEASE}.tar.gz
          wget https://github.com/EmbarkStudios/cargo-deny/releases/download/${CARGO_DENY_VERSION}/${DENY_RELEASE}.tar.gz.sha256
          EXPECTED="$(cat ${DENY_RELEASE}.tar.gz.sha256)"
          echo "${EXPECTED} ${DENY_RELEASE}.tar.gz" | sha256sum --check
          tar xvzf $DENY_RELEASE.tar.gz
          $DENY_RELEASE/cargo-deny check all

      # TODO: cargo fmt / clippy / audit / outdated check?

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: rust_compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.NO_BROWSER_CARGO_TOKEN }}"
        run: |
          sed --in-place "s/version = \"0.0.0\"/version = \"$GITHUB_REF_NAME\"/g" Cargo.toml
          cargo publish --dry-run --allow-dirty
          cargo package --list --allow-dirty
          cargo publish --allow-dirty

      - name: github release
        uses: softprops/action-gh-release@v0.1.15
        with:
          prerelease: ${{ contains(github.ref_name, '-') }}
          generate_release_notes: true
